window.AUC_ATLAS_PROFESSORS = [
  { id: "eslam-badr", name: "Eslam Badr", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785248610/ChatGPT_Image_Jul_28_2026_05_23_19_PM_xfec1d.png", department: "MACT", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Eslam Badr earned his PhD from UAB before joining AUC. His work focuses on algebraic geometry and arithmetic, including plane curves, moduli spaces, automorphism groups, twisting theory, quadratic points, and Weierstrass points." },
  { id: "ehab-el-sawy", name: "Ehab El Sawy", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785249148/Ehab_ElSawy_ifg2np.png", department: "Chemistry", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Ehab El Sawy earned his PhD in physical chemistry at the University of Calgary before joining AUC in 2017. His work focuses on nano-electrochemistry, fuel cells, hydrogen production, batteries, sensors, and corrosion protection." },
  { id: "nageh-allam", name: "Nageh Allam", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785249240/Nageh_Allam_wfaser.png", department: "Physics", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Nageh Allam earned his PhD in materials science and engineering from Penn State before joining AUC in 2011. His work focuses on nanomaterials for energy, sensors, desalination, biomaterials, and computational materials science." },
  { id: "tamer-shoeib", name: "Tamer Shoeib", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785249461/Tamer_Shoeib_qmcccs.png", department: "Chemistry", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Tamer Shoeib earned his PhD in chemistry from York University before conducting postdoctoral research in Canada. His work focuses on analytical and biophysical chemistry, molecular structure, mass spectrometry, and metal-containing biomolecules." },
  { id: "ibrahim-abotaleb", name: "Ibrahim Abotaleb", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785287149/Ibrahim_Abotaleb_awad4c.png", department: "CENG", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Ibrahim Abotaleb earned his PhD from the University of Tennessee before joining AUC. His work focuses on AI in construction, sustainability, project control, risk, optimization, and contract management." },
  { id: "hassan-azzazy", name: "Hassan Azzazy", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785286932/Hassan_Azazy_frfg0s.png", department: "Chemistry", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Hassan Azzazy earned his PhD from the University of North Texas Health Science Center before joining AUC. His work focuses on diagnostics, biosensors, nanobiotechnology, drug delivery, and clinical laboratory medicine." },
  { id: "walid-fouad", name: "Walid Fouad", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785288250/Walid_Fouad_khxyvf.png", department: "Biology", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Walid Fouad earned his PhD in plant molecular and cellular biology from the University of Florida before joining AUC. His work focuses on plant biotechnology, crop improvement, stress tolerance, algae, biofuels, and sustainable agriculture." },
  { id: "arthur-bos", name: "Arthur Bos", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785288244/Arthur_Bos_tegujk.png", department: "Biology", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Arthur Bos earned his PhD in coastal zone management and fish biology from Hamburg University before joining AUC in 2011. His work focuses on reef fish, marine protected areas, invertebrates, seagrass ecology, and habitat restoration." },
  { id: "mohamed-badran", name: "Mohamed Badran", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785288787/Mohamed_Badran_ssh771.png", department: "MENG", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Mohamed Badran earned his PhD in engineering systems and computing from the University of Guelph before joining AUC. His work focuses on operations research, optimization, autonomous vehicles, and BioMEMS sensors and actuators." },
  { id: "ahmed-abdellatif", name: "Ahmed Abdellatif", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785288910/Ahmed_Abdellatif_elvz21.png", department: "Biology", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Ahmed Abdellatif earned his MSc and PhD in anatomical sciences and neurobiology from the University of Louisville before joining AUC. His work focuses on tissue repair, diabetes, aging, dementia, and neurodegenerative diseases." },
  { id: "wafik-lotfallah", name: "Wafik Lotfallah", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785326069/Wafik_Lotfallah_to4w8v.png", department: "MACT", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Wafik Lotfallah earned his PhD from the University of Wisconsin-Madison before joining AUC in 2009. His work focuses on finite model theory, descriptive complexity, fuzzy logic, and mathematical modeling." },
  { id: "laila-el-serty", name: "Laila El Serty", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785344850/Laila_ElSerty_gf6bkr.png", department: "RHET", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Laila El Serty's professor profile can connect her courses, materials, and course-specific reviews as they are added to AUC Atlas." },
  { id: "mariah-fairley", name: "Mariah Fairley", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785344851/Mariah_Fairley_h9ykwv.png", department: "ELI", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Mariah Fairley's professor profile can connect her courses, materials, and course-specific reviews as they are added to AUC Atlas." },
  { id: "gretchen-mccullough", name: "Gretchen McCullough", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785344851/Gretchen_McCullough_ktotfl.png", department: "RHET", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Gretchen McCullough's professor profile can connect her courses, materials, and course-specific reviews as they are added to AUC Atlas." },
  { id: "kathleen-saville", name: "Kathleen Saville", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785344856/Kathleen_Saville_hz1cgi.png", department: "RHET", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Kathleen Saville's professor profile can connect her courses, materials, and course-specific reviews as they are added to AUC Atlas." },
  { id: "fikry-boutros", name: "Fikry Boutros", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785344856/Fikry_Boutros_gbqnkt.png", department: "RHET", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Fikry Boutros's professor profile can connect his courses, materials, and course-specific reviews as they are added to AUC Atlas." },
  { id: "iman-baza", name: "Iman Baza", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785344856/Iman_Baza_ohxkad.png", department: "ELI", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Iman Baza's professor profile can connect her courses, materials, and course-specific reviews as they are added to AUC Atlas." },
  { id: "alexander-lewko", name: "Alexander Lewko", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785344860/Alexander_Lewko_dexjfc.png", department: "ALA", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Alexander Lewko's professor profile can connect his courses, materials, and course-specific reviews as they are added to AUC Atlas." },
  { id: "mariam-osman", name: "Mariam Osman", image: "https://res.cloudinary.com/hpsuzs6q/image/upload/v1785344867/Mariam_Osman_rmlqxj.png", department: "ELI", rating: null, ratingLabel: "Not rated yet", reviewCount: 0, reviewLabel: "No reviews yet", bio: "Mariam Osman's professor profile can connect her courses, materials, and course-specific reviews as they are added to AUC Atlas." }
];

window.getAucAtlasProfessorById = function (id) {
  return window.AUC_ATLAS_PROFESSORS.find(function (professor) {
    return professor.id === id;
  }) || null;
};
